home:
    hero_image: "http://odi-stg.whiteag5.tryingitout.co.uk/images/odi-mask2.jpg"
    hero_text: "<p>ODI Event:</p><p>Open Data Hack Days</p>"
    links:
      -
        image: "/assets/come_join_us.png"
        link: "/join-us"
        colour: 2
      -
        frame: "/news/module"
      -
        title: "Open Data Certificates"
        image: "/assets/ODI_certs_logo.png"
        link: "https://certificates.theodi.org/"
        colour: 7
      -
        title: "Lunchtime lectures"
        background_image: "/assets/green_roundy.png"
        link: "/lunchtime-lectures"
        colour: 4
      -
        frame: "/blog/module"
      -
        frame: "/courses/module"
      -
        title: "Open Data Challenge Series"
        image: "/assets/white_spikey.png"
        link: "/challenge-series"
        colour: 9
      -
        title: "Dashboards"
        link: "http://dashboards.theodi.org/"
        colour: 3
      - 
        frame: "/events/module"
about:
    title: "About"
    hero_image: "/assets/about_hero.jpg"
    links:
     -
      title: "About the ODI"
      text: "Here is some text"
      link: "/about-us"
      colour: 10
     -
      title: "Our space"
      text: "Here is some text"
      link: "/space"
      colour: 0
     -
      title: "Data as culture"
      text: "Here is some text"
      link: "/culture"
      colour: 3
     -
       title: "FAQ"
       text: "Here is some text"
       link: "/faq"
       colour: 0
     -
       title: "Press Enquiries"
       text: "Here is some text"
       link: "/newsroom"
       colour: 7
     -
       title: "Contact us"
       text: "Here is some text"
       link: "/contact"
       colour: 0
get-involved:
     title: "Get Involved"
     hero_image: "/assets/getinvolved_hero.jpg"
     links:
      -
       title: "Membership intro"
       text: "Here is some text"
       link: "/join-us"
       colour: 10
      -
       title: "Start-ups"
       text: "Here is some text"
       link: "/start-ups"
       colour: 0
      -
       title: "ODI Challenge Series"
       text: "Here is some text"
       link: "/challenge-series"
       colour: 3
learning:
    title: "Learning"
    hero_image: "/assets/learn_hero.jpg"
    links:
     -
      title: "Upcoming Courses"
      text: "Here is some text"
      link: "/courses"
      colour: 10
     -
      title: "Post-Grad Intro"
      text: "Here is some text"
      link: "/pg-certificate"
      colour: 0
     -
      title: "Upcoming Friday Lecture"
      text: "Here is some text"
      link: "/lunchtime-lectures"
      colour: 3
     - 
      title: "Library Intro"
      text: "Here is some text"
      link: "/library"
      colour: 0
whats-happening:
    title: "What's Happening?"
    hero_image: "/assets/whatshappening_hero.jpg"
    links:
     -
      title: "Upcoming Events"
      text: "Here is some text"
      link: "/events"
      colour: 10
     -
      title: "Calendar"
      text: "Here is some text"
      link: "/calendar"
      colour: 0
     -
      title: "News"
      text: "Here is some text"
      link: "/news"
      colour: 3
     - 
      title: "Friday Lunchtime Lectures"
      text: "Here is some text"
      link: "/lunchtime-lectures"
      colour: 0
     - 
      title: "Hire the ODI space"
      text: "Here is some text"
      link: "/hire"
      colour: 7