home:
    hero_image: "about_hero.jpg"
    hero_text: "<p>The Open Data Institute</p>"
    hero_link: "http://theodi.org/about"
    hero_alt: "Knowledge for everyone"
    links:
      -
        image: "annualreport_module.jpg"
        Alt: "ODI's First Year: Annual Report"
        link: "/odis-first-year-annual-report"
      -
        image: "newmember_socrata_modules.jpg"
        link: "news/a-bigger-and-better-introducing-our-newest-members"
        alt: "Socrata: Our newest member"
      -
        frame: "/news/module"
      -
        image: "odc_modules.jpg"
        link: "https://certificates.theodi.org/"
        alt: "Open Data Certificates"
      -
        image: "20131125_burnthedigitalpaper_module.jpg"
        link: "http://theodi.org/lunchtime-lectures/friday-lunchtime-lecture-burn-the-digital-paper-a-call-to-arms"
        alt: "Latest Lunchtime Lecture: Burn the Digital Paper: A call to arms."
      -
        image: "node_module.jpg"
        link: "/nodes"
        alt: "ODI Nodes"
      -
        frame: "/blog/module"
      -
        frame: "/courses/module"
#      -
#        image: "opendatahistory_modules.jpg"
#        link: "#"
      -
        image: "globalvoice_modules.jpg"
        link: "http://summit.theodi.org/speakers/"
        alt: "Global voices at the ODI Summit"
      - 
        frame: "/events/module"
      -
        image: "training&projects_module.jpg"
        link: "/learning"
        alt: "Training and projects"
      -
        title: Introducing Open Data Partnership for Development
        text: GLOBAL PROJECTS
        link: /odp4d
        colour: 2
about:
    title: "About"
    hero_image: "about_hero.jpg"
    alt: "Knowlege for Everyone"
    links:
     -
       image: "about_module.jpg"
       link: "/about-us"
       alt: "Who are we? What do we do?"
     -
       image: "annualreport_module.jpg"
       link: "/nodes"
       alt: "ODI Annual Report 2013"
     -
       image: "jobs_module.jpg"
       link: "/jobs"
       alt: "Jobs: Join the ODI"
     -
       image: "dataasculture_module1.jpg"
       link: "/culture"
       alt: "Data as culture"
     -
       image: "faq_module.jpg"
       link: "/faq"
       alt: "Frequently Asked Questions"
     -
       image: "people_module.jpg"
       link: "/team"
       alt: "ODI People"
     -
       image: "contactus_module.jpg"
       link: "/contact"
       alt: "Contact us"
     -
       image: "press_module.jpg"
       link: "/newsroom"
       alt: "Press - enquire within"
     -
       image: "procurement_modules.jpg"
       link: "/procurement"
       alt: "Procurement"
get-involved:
     title: "Get Involved"
     hero_image: "getinvolved_hero.jpg"
     alt: "Get involved"
     links:
      -
       image: "member_module.jpg"
       link: "/join-us"
       alt: "Join us - become an ODI member"
      -
       image: "node_module.jpg"
       link: "/nodes"
       alt: "ODI nodes"
      -
       image: "odcs_modules.jpg"
       link: "/challenge-series"
       alt: "Open Data Challenge Series"
      -
       image: "consultationresponses_modules.jpg"
       link: "/consultation-responses"
       alt: "Consultation Responses"
      -
       image: "startup_module.jpg"
       link: "/start-ups"
       alt: "Startups"
      -
       image: "certificates_module.jpg"
       link: "http://certificates.theodi.org"
       alt: "Open Data Certificates"
learning:
    title: "Learning"
    hero_image: "learn_hero.jpg"
    alt: "Learn"
    links:
     -
      image: "courses_modules.jpg"
      link: "/courses"
      alt: "Courses"
     -
      image: "casestudies_modules.jpg"
      link: "/case-studies"
      alt: "Case studies"
     -
      image: "fridaylunchtimelectures_module.jpg"
      link: "/lunchtime-lectures"
      alt: "Friday Lunchtime Lectures"
     -
      image: "guides_modules.jpg"
      link: "/guides"
      alt: "Guides"
