home:
    hero_image: "/assets/homepagehero_Hero.jpg"
    hero_text: "<p>ODI Annual Summit</p><p>29th October 2013</p>"
    hero_link: "http://summit.theodi.org"
    links:
      -
        image: "/assets/newmember_socrata_modules.jpg"
        link: "http://directory.theodi.org/members"
        colour: 2
      -
        frame: "/news/module"
      -
        image: "/assets/odc_modules.jpg"
        link: "https://certificates.theodi.org/"
      -
        image: "/assets/node_module.jpg"
        link: "/nodes"
      -
        frame: "/blog/module"
      -
        frame: "/courses/module"
#      -
#        image: "/assets/opendatahistory_modules.jpg"
#        link: "#"
      -
        image: "/assets/globalvoice_modules.jpg"
        link: "http://summit.theodi.org"
      - 
        frame: "/events/module"
      -
        image: "/assets/training&projects_module.jpg"
        link: "/learning"
about:
    title: "About"
    hero_image: "/assets/about_hero.jpg"
    links:
     -
      image: "/assets/about_module.jpg"
      link: "/about-us"
     -
      image: "/assets/jobs_module.jpg"
      link: "/jobs"
     -
      image: "/assets/dataasculture_module1.jpg"
      link: "/culture"
     -
       image: "/assets/faq_module.jpg"
       link: "/faq"
     -
       image: "/assets/people_module.jpg"
       link: "/team"
     -
       image: "/assets/contactus_module.jpg"
       link: "/contact"
     -
       image: "/assets/press_module.jpg"
       link: "/newsroom"
     -
       image: "/assets/procurement_modules.jpg"
       link: "/procurement"
get-involved:
     title: "Get Involved"
     hero_image: "/assets/getinvolved_hero.jpg"
     links:
      -
       image: "/assets/member_module.jpg"
       link: "/join-us"
      -
       image: "/assets/node_module.jpg"
       link: "/nodes"
      -
       image: "/assets/odcs_modules.jpg"
       link: "/challenge-series"
      -
       image: "/assets/consultationresponses_modules.jpg"
       link: "/consultation-responses"
      -
       image: "/assets/startup_module.jpg"
       link: "/start-ups"
      -
       image: "/assets/certificates_module.jpg"
       link: "http://certificates.theodi.org"
learning:
    title: "Learning"
    hero_image: "/assets/learn_hero.jpg"
    links:
     -
      image: "/assets/courses_modules.jpg"
      link: "/courses"
     -
      image: "/assets/casestudies_modules.jpg"
      link: "/case-studies"
     -
      image: "/assets/fridaylunchtimelectures_module.jpg"
      link: "/lunchtime-lectures"
     -
      image: "/assets/guides_modules.jpg"
      link: "/guides"
